[versions]
java = "25"
springBoot = "4.1.1"
spotless = "8.10.2"
checkstyle = "14.1.0"
spotbugs = "4.10.4"
spotbugsGradlePlugin = "6.5.11"
jacoco = "0.8.15"
junit = "6.1.3"
lombok = "1.18.48"
wiremock = "3.13.2"
mongodbReactive = "5.11.1"

[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-data-mongodb-reactive = { module = "org.springframework.boot:spring-boot-starter-data-mongodb-reactive" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "springBoot" }
spotless-gradle-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
spotbugs-gradle-plugin = { module = "com.github.spotbugs:com.github.spotbugs.gradle.plugin", version.ref = "spotbugsGradlePlugin" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
wiremock-standalone = { module = "org.wiremock:wiremock-standalone", version.ref = "wiremock" }
mongodb-driver-reactivestreams = { module = "org.mongodb:mongodb-driver-reactivestreams", version.ref = "mongodbReactive" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
